spring:
  application:
    name: OPEN-BI-AI-ANALYTICS-SERVICE
  config:
    import: configserver:http://localhost:8080
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
server:
  port: 8003
  address: 0.0.0.0
  servlet:
    context-path: /api
logging:
  config: classpath:logback-spring.xml # Logback configuration file
  level:
    org:
      springframework:
        cloud:
          loadbalancer:
            cache: debug
    com:
      glenncai:
        openbiplatform:
          aianalytics:
            mapper: trace