spring:
  application:
    name: OPEN-BI-USER-SERVICE
server:
  port: 8001
  address: 0.0.0.0
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000 # Expires in 30 days
logging:
  config: classpath:logback-spring.xml # Logback configuration file
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}