### User Service API

### User register
POST http://localhost:8000/api/user/register
Accept: application/json
Content-Type: application/json

{
  "username": "user1",
  "password": "test123456!",
  "confirmPassword": "test123456!"
}

###

### User login
POST http://localhost:8000/api/user/login
Accept: application/json
Content-Type: application/json

{
  "username": "user1",
  "password": "test123456!"
}

###

### Get user login info
POST http://localhost:8000/api/user/get/login
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

###

### Add user (admin only)
POST http://localhost:8000/api/user/add
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "admin",
  "password": "test123456!",
  "role": "admin"
}

###

### Disable user (admin only)
POST http://localhost:8000/api/user/disable
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "user"
}

###

### Enable user (admin only)
POST http://localhost:8000/api/user/enable
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "user"
}

###

### Get user info by user id
GET http://localhost:8000/api/user/get/1698906542983110657
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

