spring:
  application:
    name: OPEN-BI-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/glenncai/open-bi-platform-config
          clone-on-start: true
    loadbalancer:
      cache:
        enabled: true
        caffeine:
          spec: initialCapacity=100,maximumSize=500,expireAfterAccess=600s,expireAfterWrite=600s
server:
  port: 8080
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}