spring:
  application:
    name: OPEN-BI-GATEWAY
  config:
    import: configserver:http://localhost:8080
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOriginPatterns: '*'
            maxAge: 3600
      routes:
        - id: OPEN-BI-USER-SERVICE
          uri: lb://OPEN-BI-USER-SERVICE
          predicates:
            - Path=/api/user/**
        - id: OPEN-BI-IP-SERVICE
          uri: lb://OPEN-BI-IP-SERVICE
          predicates:
            - Path=/api/ip/**
        - id: OPEN-BI-AI-KEY-SERVICE
          uri: lb://OPEN-BI-AI-KEY-SERVICE
          predicates:
            - Path=/api/aikey/**
        - id: OPEN-BI-AI-ANALYTICS-SERVICE
          uri: lb://OPEN-BI-AI-ANALYTICS-SERVICE
          predicates:
            - Path=/api/aianalytics/**
server:
  port: 8000
logging:
  config: classpath:logback-spring.xml # Logback configuration file
  level:
    org:
      springframework:
        cloud:
          loadbalancer:
            cache: debug
