spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
      enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 10s
    password: test123456!
  cache:
    type: redis
    redis:
      time-to-live: 86400s # 1 day
      use-key-prefix: true
      key-prefix: openbi_cache_
      cache-null-values: false
  datasource:
    url: jdbc:mysql://localhost:3306/bi?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Hong_Kong
    username: root
    password: test123456!
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: valid
      logic-delete-value: 0
      logic-not-delete-value: 1
  mapper-locations: classpath:mapper/*.xml
feign:
  httpclient:
    enabled: true