spring:
  application:
    name: OPEN-BI-USER-SERVICE
  config:
    import: configserver:http://localhost:8080
server:
  port: 8001
  address: 0.0.0.0
  servlet:
    context-path: /api
logging:
  config: classpath:logback-spring.xml # Logback configuration file
  level:
    org:
      springframework:
        cloud:
          loadbalancer:
            cache: debug
    com:
      glenncai:
        openbiplatform:
          user:
            mapper: trace